import { RawSkillDefinition } from "./types";

// Auto-generated by scripts/import-skills.py from 技能规范化（v1）.xlsx.
export const RAW_SKILL_CATALOG: RawSkillDefinition[] = [
  {
    "id": "skill_2_8724",
    "name": "空",
    "fusion": "",
    "timing": "无",
    "description": "无效果",
    "tags": [],
    "sourceRow": 2
  },
  {
    "id": "skill_3_56718",
    "name": "再来一次",
    "fusion": "",
    "timing": "随时可用",
    "description": "重新抽取一次技能",
    "tags": [],
    "sourceRow": 3
  },
  {
    "id": "skill_4_65637",
    "name": "沙子",
    "fusion": "",
    "timing": "随时可用",
    "description": "变换为一个自选小技能，使用时需声明为沙子变化。若场上有其他玩家持有该技能，你本次变幻失败，你退游",
    "tags": [],
    "sourceRow": 4
  },
  {
    "id": "skill_5_34881",
    "name": "封印",
    "fusion": "",
    "timing": "随时可用",
    "description": "其他玩家暴露锁定技后，你可将其封锁，每个玩家只能封锁一个",
    "tags": [],
    "sourceRow": 5
  },
  {
    "id": "skill_6_503",
    "name": "裂魂",
    "fusion": "",
    "timing": "被动技能",
    "description": "你杀死玩家后，他无法复活",
    "tags": [],
    "sourceRow": 6
  },
  {
    "id": "skill_7_35434",
    "name": "净化",
    "fusion": "",
    "timing": "被动技能",
    "description": "其他玩家的限定技对你无效",
    "tags": [],
    "sourceRow": 7
  },
  {
    "id": "skill_8_89763",
    "name": "禁锢",
    "fusion": "",
    "timing": "被动技能",
    "description": "当你在场时，全场控制技被封锁",
    "tags": [],
    "sourceRow": 8
  },
  {
    "id": "skill_9_93219",
    "name": "破厄",
    "fusion": "",
    "timing": "被动技能",
    "description": "当你持有该技能时，开场时进行声明，当你在场时，全场封印、净化、禁锢、裂魂、沦陷、衰竭、血之哀无效",
    "tags": [],
    "sourceRow": 9
  },
  {
    "id": "skill_10_9488",
    "name": "沦陷",
    "fusion": "",
    "timing": "随时可用",
    "description": "一局限2次，先制重开，下轮所有玩家无技能",
    "tags": [],
    "sourceRow": 10
  },
  {
    "id": "skill_11_89360",
    "name": "衰竭",
    "fusion": "",
    "timing": "被动技能",
    "description": "全场含有0和无限的出招失效",
    "tags": [],
    "sourceRow": 11
  },
  {
    "id": "skill_12_79004",
    "name": "血之哀",
    "fusion": "",
    "timing": "被动技能",
    "description": "当你在场时，所有玩家无法加血",
    "tags": [],
    "sourceRow": 12
  },
  {
    "id": "skill_13_68869",
    "name": "火烧大地",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限1次，使除你外所有人受到1点火系法伤，消除除你外所有人的冰系技能，对持有冰系技能的玩家变为使其受到2点火系法伤",
    "tags": [
      "火系技能"
    ],
    "sourceRow": 13
  },
  {
    "id": "skill_14_46860",
    "name": "霜落大地",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限1次，使你+4血，除你外所有人+1血，消除除你外所有人的火系技能，对持有火系技能的玩家不加血",
    "tags": [
      "冰系技能"
    ],
    "sourceRow": 14
  },
  {
    "id": "skill_15_64971",
    "name": "净化之风",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限2次，第一次使用时使除你外所有血量为奇数的玩家-1血，第二次使用时使除你外所有血量为偶数的玩家-1血",
    "tags": [],
    "sourceRow": 15
  },
  {
    "id": "huo_yan_dao",
    "name": "火焰刀",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的单个杀攻2，等级2，变为火系",
    "tags": [
      "火系技能"
    ],
    "sourceRow": 16
  },
  {
    "id": "zhu_que_yu_shan",
    "name": "朱雀羽扇",
    "fusion": "",
    "timing": "被动技能",
    "description": "朱雀羽扇：锁定技，你的单个擒攻4，等级1，变为火系；火系技能",
    "tags": [
      "火系技能"
    ],
    "sourceRow": 17
  },
  {
    "id": "skill_18_34323",
    "name": "寒冰剑",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，使你的攻击变为冰系，命中后不会造成伤害（但仍然会重开），使目标技能失效1轮",
    "tags": [
      "冰系技能"
    ],
    "sourceRow": 18
  },
  {
    "id": "skill_19_45609",
    "name": "毒箭雨",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的万箭齐发变为毒系，只能用石头防，不会被反弹",
    "tags": [
      "毒系技能"
    ],
    "sourceRow": 19
  },
  {
    "id": "skill_20_63089",
    "name": "冰箭雨",
    "fusion": "",
    "timing": "被动技能；印记使用：回合中",
    "description": "锁定技，你的万箭齐发变为冰系，不会被反弹，命中后赋予1层“冰雨”印记；回合中，当你受到其他玩家的攻击时，若他有“冰雨”印记，可以消耗1层，使其对你的攻击-2",
    "tags": [
      "冰系技能"
    ],
    "sourceRow": 20
  },
  {
    "id": "skill_21_36332",
    "name": "熔岩之怒",
    "fusion": "",
    "timing": "被动技能；印记使用：回合中",
    "description": "锁定技，你每出3次石头，获得1层“熔岩”印记，最高3层；回合中，当你使用攻击时，可以消耗x层，使该攻击变为火系，攻等+x",
    "tags": [
      "火系技能"
    ],
    "sourceRow": 21
  },
  {
    "id": "skill_22_54978",
    "name": "凛冬之怒",
    "fusion": "",
    "timing": "被动技能；印记使用：回合中",
    "description": "锁定技，你每出3次油条，获得1层“凛冬”印记，最高3层；回合中，当你使用攻击时，可以消耗x层，使该攻击变为冰系，攻击-x，等级+x，命中后赋予x回合“冰冻”；冰冻：无法出招；",
    "tags": [
      "冰系技能"
    ],
    "sourceRow": 22
  },
  {
    "id": "skill_23_90895",
    "name": "神隐红莲",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你濒死时，+1血",
    "tags": [],
    "sourceRow": 23
  },
  {
    "id": "skill_24_71363",
    "name": "神隐青莲",
    "fusion": "",
    "timing": "随时可用",
    "description": "控制技，当你濒死时，可以消耗3饼，+3血，下轮轮初+1饼",
    "tags": [],
    "sourceRow": 24
  },
  {
    "id": "skill_25_51277",
    "name": "暗影盾",
    "fusion": "",
    "timing": "回合中",
    "description": "限定技，一局限1次，免疫此回合受到的不超过无限的攻击，+8防御值",
    "tags": [],
    "sourceRow": 25
  },
  {
    "id": "skill_26_70243",
    "name": "后盾",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你对补刀者无敌",
    "tags": [],
    "sourceRow": 26
  },
  {
    "id": "skill_27_23816",
    "name": "全力一击",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，0饼，攻无限，-1级，任意防，被防住则你-3血",
    "tags": [],
    "sourceRow": 27
  },
  {
    "id": "skill_28_42646",
    "name": "狙击枪",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你补刀时，伤害×2",
    "tags": [],
    "sourceRow": 28
  },
  {
    "id": "skill_29_96125",
    "name": "古淀刀",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你的攻击命中目标时，若目标饼数≤0，你造成的伤害×2",
    "tags": [],
    "sourceRow": 29
  },
  {
    "id": "skill_30_38815",
    "name": "青釭剑",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的攻击无视换防、幻防、八卦阵、藤甲、无形之盾、神之庇佑",
    "tags": [],
    "sourceRow": 30
  },
  {
    "id": "skill_31_80497",
    "name": "双刃剑",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，当你的攻击被非反弹防住时，你可以-1血，使该攻击无视其防御出招",
    "tags": [],
    "sourceRow": 31
  },
  {
    "id": "skill_32_19017",
    "name": "神之庇护",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，每轮前2回合无敌",
    "tags": [],
    "sourceRow": 32
  },
  {
    "id": "skill_33_55159",
    "name": "神族水晶",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你出招后，若出招有等级，出招总等级+1",
    "tags": [],
    "sourceRow": 33
  },
  {
    "id": "skill_34_1533",
    "name": "酒",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你出招后，若出招有攻击，出招总攻击+1",
    "tags": [],
    "sourceRow": 34
  },
  {
    "id": "skill_35_16792",
    "name": "雷电法术",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限2次，对除你外血量最高的2名玩家造成2点电系法伤，当有＞2名血量最高玩家时，由你选择伤害目标",
    "tags": [
      "电系技能"
    ],
    "sourceRow": 35
  },
  {
    "id": "skill_36_14343",
    "name": "电击法术",
    "fusion": "",
    "timing": "出招",
    "description": "限定技，一局限1次，技能出招，选取1到2名玩家作为目标，等级无限，反弹防，命中后使其麻痹1回合；麻痹：若目标被麻痹时出招为防御，则固定此防御作为出招；若目标出招为饼，则固定饼作为出招，但是不会加饼；其他情况下，视为没有出招",
    "tags": [
      "电系技能"
    ],
    "sourceRow": 36
  },
  {
    "id": "skill_37_68416",
    "name": "鬼道",
    "fusion": "",
    "timing": "被动技能；资源使用：出招",
    "description": "锁定技，当你使用小防防住他人攻击时，根据攻击重数获得等量的“鬼道”次数；鬼道：技能出招，攻1，2级，油条防，电系",
    "tags": [
      "电系技能"
    ],
    "sourceRow": 37
  },
  {
    "id": "skill_38_81245",
    "name": "闪电护体",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你受到多个攻击不超过无限的攻击时，只承受其中攻击最低的1个攻击",
    "tags": [
      "电系技能"
    ],
    "sourceRow": 38
  },
  {
    "id": "skill_39_77400",
    "name": "大地之心",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你受到电系出招时，你免疫该出招，并+4防御值",
    "tags": [],
    "sourceRow": 39
  },
  {
    "id": "skill_40_27274",
    "name": "碎石掌",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，3饼，攻3，2级，小防防，目标出石头时攻击变为6",
    "tags": [],
    "sourceRow": 40
  },
  {
    "id": "skill_41_43495",
    "name": "裂山拳",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，3饼，攻2，3级，油条防，目标出石头时攻击变为4",
    "tags": [],
    "sourceRow": 41
  },
  {
    "id": "skill_42_94266",
    "name": "破地之力",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，全场攻击大于2、小于6的攻击无效",
    "tags": [],
    "sourceRow": 42
  },
  {
    "id": "skill_43_74082",
    "name": "阳光普照",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，全场攻击大于4的攻击无效",
    "tags": [],
    "sourceRow": 43
  },
  {
    "id": "skill_44_20092",
    "name": "永远之夜",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，全场攻击小于4的攻击无效",
    "tags": [],
    "sourceRow": 44
  },
  {
    "id": "skill_45_30424",
    "name": "毁灭之力",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，2轮限1次，当你攻击时，可以将该攻击的攻击+1、等级-1；攻击-1、等级+1；攻击+2、等级-2；攻击-2、等级+2；攻击变为0、等级×4；攻击×3、等级变为0",
    "tags": [],
    "sourceRow": 45
  },
  {
    "id": "skill_46_3651",
    "name": "嗜血",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你的攻击造成x点伤害时，你+x/4（下取整）点生命",
    "tags": [],
    "sourceRow": 46
  },
  {
    "id": "skill_47_94841",
    "name": "凝血之力",
    "fusion": "",
    "timing": "轮间",
    "description": "限定技，一局限2次，若你上一轮共受到x点伤害，本轮轮初+x饼，加饼上限为4",
    "tags": [],
    "sourceRow": 47
  },
  {
    "id": "skill_48_26455",
    "name": "血水屏障",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限2次，你-1血，+4防御值",
    "tags": [],
    "sourceRow": 48
  },
  {
    "id": "skill_49_75347",
    "name": "遗计",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你上一轮受到过伤害时，本轮轮初+2饼",
    "tags": [],
    "sourceRow": 49
  },
  {
    "id": "skill_50_50034",
    "name": "八卦阵",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你受到攻击时，受到的攻击伤害-1",
    "tags": [],
    "sourceRow": 50
  },
  {
    "id": "skill_51_92674",
    "name": "藤甲",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你免疫杀、万箭齐发、南蛮入侵，但当攻击为火系时无法免疫且受到伤害+1",
    "tags": [],
    "sourceRow": 51
  },
  {
    "id": "skill_52_22171",
    "name": "克己",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你本轮未使用过攻击时，保留1/3（向下取整）的饼至下轮轮初",
    "tags": [],
    "sourceRow": 52
  },
  {
    "id": "skill_53_62958",
    "name": "独裁",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你每轮轮初+1饼",
    "tags": [],
    "sourceRow": 53
  },
  {
    "id": "skill_54_99719",
    "name": "乱舞",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你所有以他人为目标的出招，目标变更为除你外所有人",
    "tags": [],
    "sourceRow": 54
  },
  {
    "id": "skill_55_96047",
    "name": "神罩",
    "fusion": "",
    "timing": "回合中",
    "description": "限定技，一局限3次，抵挡本回合受到的普通攻击",
    "tags": [],
    "sourceRow": 55
  },
  {
    "id": "skill_56_42637",
    "name": "鬼罩",
    "fusion": "",
    "timing": "回合中",
    "description": "限定技，一局限3次，抵挡本回合受到的技能出招",
    "tags": [],
    "sourceRow": 56
  },
  {
    "id": "skill_57_59843",
    "name": "绝弹",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的反弹可以反弹核爆、超核爆、技能攻击",
    "tags": [],
    "sourceRow": 57
  },
  {
    "id": "skill_58_88471",
    "name": "散弹",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的反弹会将受到的攻击反弹给除你外所有人",
    "tags": [],
    "sourceRow": 58
  },
  {
    "id": "skill_59_79990",
    "name": "火眼金睛",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的所有非反弹防的出招破弹",
    "tags": [],
    "sourceRow": 59
  },
  {
    "id": "skill_60_57192",
    "name": "烈弓",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，当你的攻击和他人的目标包含你的出招相撞时，你可以让两者交错而过，不视为补刀",
    "tags": [],
    "sourceRow": 60
  },
  {
    "id": "skill_61_59049",
    "name": "圣",
    "fusion": "",
    "timing": "出招",
    "description": "技能出招，x饼，+2x饼",
    "tags": [],
    "sourceRow": 61
  },
  {
    "id": "skill_62_8008",
    "name": "齐天大圣",
    "fusion": "",
    "timing": "出招",
    "description": "技能出招，x饼，+3x饼，出圣且受到攻击伤害时，直接变为0血，已经0血时该效果不触发",
    "tags": [],
    "sourceRow": 62
  },
  {
    "id": "skill_63_72549",
    "name": "圣水收集器",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，第4x回合回合初+1饼",
    "tags": [],
    "sourceRow": 63
  },
  {
    "id": "skill_64_60978",
    "name": "治愈术",
    "fusion": "",
    "timing": "死亡时",
    "description": "限定技，限1次，满血复活",
    "tags": [],
    "sourceRow": 64
  },
  {
    "id": "skill_65_71994",
    "name": "浴火重生",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你受到致死伤害时，若该伤害为火系，或者若此时你有4饼，满血复活",
    "tags": [],
    "sourceRow": 65
  },
  {
    "id": "skill_66_82448",
    "name": "天佑之魂",
    "fusion": "",
    "timing": "随时可用，死亡时可用",
    "description": "限定技，限1次，对当前血量取绝对值后再+6，视为复活",
    "tags": [],
    "sourceRow": 66
  },
  {
    "id": "skill_67_31717",
    "name": "沐浴圣光",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的初始血量×3",
    "tags": [],
    "sourceRow": 67
  },
  {
    "id": "skill_68_57581",
    "name": "离殇",
    "fusion": "",
    "timing": "死亡时",
    "description": "限定技，限1次，选取对你造成致死伤害的玩家之一，若他有x血，他变为x/2（向下取整）血，你x/2（向上取整）血复活，并夺取他一条指定的已暴露小技能",
    "tags": [],
    "sourceRow": 68
  },
  {
    "id": "skill_69_22138",
    "name": "绝对值",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的血量变为负数时，立即取绝对值，视为复活。你的血量变为0时，你死亡",
    "tags": [],
    "sourceRow": 69
  },
  {
    "id": "skill_70_79685",
    "name": "死神之镰",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当场上除你外玩家死亡时，每个伤害为x的致死伤害使你+x/2（向下取整）血",
    "tags": [],
    "sourceRow": 70
  },
  {
    "id": "skill_71_40087",
    "name": "圣域",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，第3x轮轮末，你+3血",
    "tags": [],
    "sourceRow": 71
  },
  {
    "id": "skill_72_53933",
    "name": "邪域",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，第3x轮轮末，你选取1名玩家，吸取他1血",
    "tags": [],
    "sourceRow": 72
  },
  {
    "id": "skill_73_76567",
    "name": "十字守护",
    "fusion": "",
    "timing": "被动技能；印记使用：回合中",
    "description": "控制技，当你受到攻击伤害时，获得1层“护佑”印记与1层“十字”印记；回合中，当你受到攻击伤害时，你可消耗1层“护佑”印记，使受到伤害÷2（下取整）；回合中，当与你相邻的玩家受到攻击伤害时，你可消耗1层“十字”印记，使其受到伤害×2",
    "tags": [],
    "sourceRow": 73
  },
  {
    "id": "skill_74_34920",
    "name": "绝对守护",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，对场上耗饼为x的非群体攻击，你可消耗x/2（向上取整）饼使其变为群体攻击；对场上耗饼为x的群体攻击，你可消耗x/2（向上取整）饼使其变为对你一人的单体攻击",
    "tags": [],
    "sourceRow": 74
  },
  {
    "id": "skill_75_68329",
    "name": "圣灵之境",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你免疫属性伤害和效果（冰、火、电、毒等）",
    "tags": [],
    "sourceRow": 75
  },
  {
    "id": "skill_76_76044",
    "name": "帝炎之境",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你受伤时，使所有对你造成伤害的玩家受到1点火系伤害；火系技能",
    "tags": [],
    "sourceRow": 76
  },
  {
    "id": "skill_77_30612",
    "name": "森林的低吟",
    "fusion": "",
    "timing": "出招",
    "description": "技能出招，3饼，此回合无敌，+3血",
    "tags": [],
    "sourceRow": 77
  },
  {
    "id": "skill_78_18866",
    "name": "火球",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，2饼，攻4，2级，油条防，火系，若未防住对目标相邻玩家溅射1点火系伤害，若相邻玩家出招为石头则不受该伤害，你不受来自自己的溅射伤害",
    "tags": [
      "火系技能"
    ],
    "sourceRow": 78
  },
  {
    "id": "skill_79_36319",
    "name": "火箭",
    "fusion": "",
    "timing": "出招",
    "description": "限定技，一局限1次，技能攻击，攻6，6级，石头防，破弹，火系，可选取连续的1到2名玩家作为目标",
    "tags": [
      "火系技能"
    ],
    "sourceRow": 79
  },
  {
    "id": "skill_80_20445",
    "name": "核反应堆",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你的核爆和超核爆消耗饼数-3",
    "tags": [],
    "sourceRow": 80
  },
  {
    "id": "skill_81_59663",
    "name": "撸",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，1饼，攻1，1级，小防防，每次命中后你的单个撸的攻等永久+1，上限为4",
    "tags": [],
    "sourceRow": 81
  },
  {
    "id": "skill_82_45540",
    "name": "日",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，1饼，攻1，2级，油条防",
    "tags": [],
    "sourceRow": 82
  },
  {
    "id": "skill_83_32356",
    "name": "丁",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，1饼，攻1，饼防，与攻击对撞则完全抵消，与抠对撞则你被退游",
    "tags": [],
    "sourceRow": 83
  },
  {
    "id": "skill_84_6114",
    "name": "抠",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击：2饼，攻1，3级，石头防，若目标出招为反弹，且反弹对象包含你，则你受到3点伤害，若与丁对撞，则使目标退游",
    "tags": [],
    "sourceRow": 84
  },
  {
    "id": "skill_85_26345",
    "name": "钟",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，1饼，攻1，2级，小防防，命中则获得1个对目标的“金钟罩”护盾，对同一名玩家的“金钟罩”最多持有1个；你受到来自他人的攻击时，若你未防住，且你有对他的“金钟罩”，则消耗这个金钟罩，抵挡这次攻击",
    "tags": [],
    "sourceRow": 85
  },
  {
    "id": "skill_86_14131",
    "name": "梵",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，2饼，攻1，2级，石头防，破弹",
    "tags": [],
    "sourceRow": 86
  },
  {
    "id": "skill_87_44771",
    "name": "连爆",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，2饼，攻1，2级，油条防，命中则获得1次免费“连爆”",
    "tags": [],
    "sourceRow": 87
  },
  {
    "id": "skill_88_62906",
    "name": "换防",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，若你的出招为小防，你可以消耗1饼，切换为油条；若你的出招为油条，你可以消耗1饼，切换为小防；",
    "tags": [],
    "sourceRow": 88
  },
  {
    "id": "skill_89_99375",
    "name": "幻防",
    "fusion": "",
    "timing": "回合中",
    "description": "幻防：控制技，若你的出招为小防，你可以消耗2饼，切换为油条；或者消耗3饼，切换为石头；若你的出招为油条，你可以消耗2饼，切换为小防或石头；若你的出招为石头，你可以消耗2饼，切换为油条；或者消耗3饼，切换为小防",
    "tags": [],
    "sourceRow": 89
  },
  {
    "id": "skill_90_32911",
    "name": "杀换",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，若你的出招为x杀，你可以消耗1饼，将其变换为x擒；若你的出招为x擒，你可以消耗1饼，将其变换为x杀",
    "tags": [],
    "sourceRow": 90
  },
  {
    "id": "skill_91_89631",
    "name": "级换",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，你可以将你的出招的攻击和等级交换",
    "tags": [],
    "sourceRow": 91
  },
  {
    "id": "skill_92_26484",
    "name": "文明人",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，场上有人说脏话是，你+1血，不重开，不声明",
    "tags": [],
    "sourceRow": 92
  },
  {
    "id": "skill_93_50224",
    "name": "逆转",
    "fusion": "",
    "timing": "回合中",
    "description": "限定技，一局限1次，逆转所有出招的发出者和目标；可使用3个逆转将自己从退游状态逆转为进游，可使用5个逆转将1人的非常规胜利逆转为失败",
    "tags": [],
    "sourceRow": 93
  },
  {
    "id": "skill_94_627",
    "name": "斗转星移",
    "fusion": "",
    "timing": "回合中",
    "description": "限定技，一局限2次，受到≤3的攻击伤害时，选定一名玩家，将该伤害转移给该玩家",
    "tags": [],
    "sourceRow": 94
  },
  {
    "id": "skill_95_91337",
    "name": "卷子",
    "fusion": "",
    "timing": "出招",
    "description": "限定技，一局限1次，技能攻击，攻退游，等同，任意防，破弹",
    "tags": [],
    "sourceRow": 95
  },
  {
    "id": "skill_96_33279",
    "name": "暴风雪",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，2饼，攻2+2，2级，油条防，冰系",
    "tags": [
      "冰系技能"
    ],
    "sourceRow": 96
  },
  {
    "id": "skill_97_60773",
    "name": "狂风骤雪",
    "fusion": "",
    "timing": "出招",
    "description": "限定技，一局限2次，技能攻击，群攻2，2级，油条防，冰系",
    "tags": [
      "冰系技能"
    ],
    "sourceRow": 97
  },
  {
    "id": "skill_98_7182",
    "name": "普天同庆",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你所有攻击变为群体攻击，但目标不包含距你最远的1或2人（3人及以下无效）；你的擒消耗1/2个饼",
    "tags": [],
    "sourceRow": 98
  },
  {
    "id": "skill_99_65551",
    "name": "无形之盾",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你对身边2人无敌（3人及以下无效）",
    "tags": [],
    "sourceRow": 99
  },
  {
    "id": "skill_100_45717",
    "name": "顺手牵羊",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，开局声明，使相邻玩家各告知你1个技能，选择其中1个获得",
    "tags": [],
    "sourceRow": 100
  },
  {
    "id": "skill_101_4254",
    "name": "镜像法术",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限1次，复制场上已暴露的1个技能",
    "tags": [],
    "sourceRow": 101
  },
  {
    "id": "skill_102_5546",
    "name": "自爆者死",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，除你外自爆者退游，你每次自爆只-1血，你有1次后手自爆机会",
    "tags": [],
    "sourceRow": 102
  },
  {
    "id": "skill_103_56259",
    "name": "闪现",
    "fusion": "",
    "timing": "回合中",
    "description": "控制技，3轮限1次，回避此回合受到的所有不超过无限的攻击",
    "tags": [],
    "sourceRow": 103
  },
  {
    "id": "skill_104_71181",
    "name": "过往时空",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限1次，先手重开，进入小空间“过往时空”5轮",
    "tags": [],
    "sourceRow": 104
  },
  {
    "id": "skill_105_48309",
    "name": "白板",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，场上剩余2人时，你胜利",
    "tags": [],
    "sourceRow": 105
  },
  {
    "id": "skill_106_59962",
    "name": "黑板",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，若白板胜利，你使其失败，你胜利",
    "tags": [],
    "sourceRow": 106
  },
  {
    "id": "skill_107_53513",
    "name": "雷裂残阳",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限1次，使除你外所有血量≤3的玩家退游，电系",
    "tags": [
      "电系技能"
    ],
    "sourceRow": 107
  },
  {
    "id": "skill_108_76133",
    "name": "六芒星",
    "fusion": "",
    "timing": "回合中",
    "description": "限定技，一局限1次，免疫此回合不超过无限的伤害，若此回合最高受到x点单次伤害，你+x+6血",
    "tags": [],
    "sourceRow": 108
  },
  {
    "id": "skill_109_65084",
    "name": "传音入密",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，他人暴露1个技能时，对其造成2点法术伤害，不重开，对每个玩家最多触发1次",
    "tags": [],
    "sourceRow": 109
  },
  {
    "id": "skill_110_2190",
    "name": "三千雷动",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，3饼，群攻4，4级，油条防，电系",
    "tags": [
      "电系技能"
    ],
    "sourceRow": 110
  },
  {
    "id": "skill_111_51056",
    "name": "制衡",
    "fusion": "",
    "timing": "随时可用",
    "description": "限定技，一局限1次，选择除你外2名玩家，设你和他们血量总和为x，若x mod 3=0或1，你的血量变为x/3（上取整），他们的血量变为x/3（下取整）；若x mod 3=2，你的血量变为x/3（下取整），他们的血量变为x/3（上取整）",
    "tags": [],
    "sourceRow": 111
  },
  {
    "id": "skill_112_30527",
    "name": "地狱使徒",
    "fusion": "",
    "timing": "有玩家死亡时",
    "description": "限定技，一局限2次，若场上有玩家死亡且没有复活，使其6血复活，无技能，成为你的傀儡；可对自己使用",
    "tags": [],
    "sourceRow": 112
  },
  {
    "id": "skill_113_88141",
    "name": "无限战意",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你死亡且没有复活后，继续游戏2轮",
    "tags": [],
    "sourceRow": 113
  },
  {
    "id": "skill_114_87583",
    "name": "不死金身",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你免疫伤害不为1的致死攻击伤害",
    "tags": [],
    "sourceRow": 114
  },
  {
    "id": "skill_115_74459",
    "name": "同生共死",
    "fusion": "",
    "timing": "回合中",
    "description": "限定技，一局限2次，选取1名玩家，若你本回合受到x点伤害，使其受到等量法术伤害",
    "tags": [],
    "sourceRow": 115
  },
  {
    "id": "skill_116_97172",
    "name": "复仇之刃",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当其他玩家对你造成攻击伤害后，若你对他造成攻击伤害，记为1次复仇；你复仇5次后胜利",
    "tags": [],
    "sourceRow": 116
  },
  {
    "id": "skill_117_55768",
    "name": "百炼成神",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，你在血量不超过初始血量的1/2（下取整）时累计攻击25次后，胜利",
    "tags": [],
    "sourceRow": 117
  },
  {
    "id": "skill_118_53580",
    "name": "冰漩决",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，3饼，攻1，3级，石头防，冰系，命中后赋予1回合“冰冻”，可选取连续的1到3名玩家作为目标；冰冻：无法出招",
    "tags": [
      "冰系技能"
    ],
    "sourceRow": 118
  },
  {
    "id": "skill_119_78843",
    "name": "火漩决",
    "fusion": "",
    "timing": "出招",
    "description": "技能攻击，3饼，攻3，3级，石头防，火系，可选取连续的1到3名玩家作为目标",
    "tags": [
      "火系技能"
    ],
    "sourceRow": 119
  },
  {
    "id": "skill_120_85509",
    "name": "创伤聚合",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，当你受到伤害后，3轮后+3血，该轮轮初+1饼",
    "tags": [],
    "sourceRow": 120
  },
  {
    "id": "skill_121_59557",
    "name": "因果律认知",
    "fusion": "",
    "timing": "被动技能",
    "description": "锁定技，开局声明，当场上玩家触发隐性技能效果时，使该技能暴露",
    "tags": [],
    "sourceRow": 121
  }
];
